#define CACHEFLUSH_TYPE CACHEFLUSH_GENERIC
#define DMABUF_IMPORT_PHYSHEAP_ID  0
#define FIX_DUSTS_POW_ON_INIT
#define GPUVIRT_VALIDATION_NUM_OS 8
#define GPU_VIRTUALIZATION_NUM_OS
#define HWR_DEFAULT_ENABLED
#define LDM_PLATFORM
#define LINUX
#define PVRSRV_ENABLE_PROCESS_STATS
#define PVRSRV_FULL_SYNC_TRACKING_HISTORY_LEN 256
#define PVRSRV_MODNAME "pvrsrvkm"
#define PVRSRV_UNMAP_ON_SPARSE_CHANGE
#define PVRSRV_USE_VMAP_FOR_KERNEL_MAPPINGS
#define PVR_BUILD_DIR "mt8173_linux"
#define PVR_DRM_DRIVER_NAME "pvr"
#define PVR_LDM_DRIVER_REGISTRATION_NAME "pvrsrvkm"
#define PVR_LINUX_ARM_PAGEALLOC_FLUSH_THRESHOLD  256
#define PVR_LINUX_HIGHORDER_ALLOCATION_THRESHOLD  256
#define PVR_LINUX_KMALLOC_ALLOCATION_THRESHOLD  16384
#define PVR_LINUX_MISR_USING_PRIVATE_WORKQUEUE
#define PVR_LINUX_PHYSMEM_MAX_ALLOC_ORDER_NUM  2
#define PVR_LINUX_PHYSMEM_MAX_POOL_PAGES 10240
#define PVR_LINUX_TIMERS_USING_WORKQUEUES
#define PVR_LINUX_USING_WORKQUEUES
#define PVR_MMAP_USE_VM_INSERT
#define RGX_BNC_CONFIG_KM_HEADER "configs/rgxconfig_km_4.V.2.51.h"
#define SUPPORT_DBGDRV_EVENT_OBJECTS
#define SUPPORT_DMABUF
#define SUPPORT_DRM
#define SUPPORT_LINUX_X86_PAT
#define SUPPORT_LINUX_X86_WRITECOMBINE
#define SUPPORT_PERCONTEXT_FREELIST
#define SUPPORT_RGX 1
#define SUPPORT_SECURE_EXPORT
#define SUPPORT_SERVER_SYNC
#define SYS_USING_INTERRUPTS
#ifdef CONFIG_DRM_POWERVR_ROGUE_DEBUG
#define DEBUG
#define DEBUG_BRIDGE_KM
#define DEBUG_HANDLEALLOC_KM
#define DEBUG_LINUX_MEMORY_ALLOCATIONS
#define DEBUG_LINUX_MEM_AREAS
#define DEBUG_LINUX_MMAP_AREAS
#define PVR_BUILD_TYPE "debug"
#define PVR_RI_DEBUG
#define RGXFW_ALIGNCHECKS
#define SUPPORT_PAGE_FAULT_DEBUG
#else
#define PVR_BUILD_TYPE "release"
#define RELEASE
#endif
#ifdef CONFIG_DRM_POWERVR_ROGUE_MT8173E1
#define RGX_BVNC_CORE_KM_HEADER "cores/rgxcore_km_4.29.2.51.h"
#else
#define RGX_BVNC_CORE_KM_HEADER "cores/rgxcore_km_4.40.2.51.h"
#endif
